# Generated by Django 5.1.5 on 2025-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0003_remove_employee_user_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='社員番号'),
        ),
    ]
