# Generated by Django 5.1.5 on 2025-01-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0005_employee_dynamic_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カスタムフィールド名')),
                ('is_required', models.BooleanField(default=False, verbose_name='必須項目')),
                ('field_type', models.CharField(choices=[('text', 'テキスト'), ('number', '数値'), ('date', '日付')], default='text', max_length=20, verbose_name='フィールドタイプ')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='dynamic_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='カスタムフィールド値'),
        ),
    ]
