# Generated by Django 5.1.5 on 2025-01-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会社名')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='会社ロゴ')),
                ('address', models.TextField(verbose_name='住所')),
                ('phone', models.CharField(max_length=15, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('contact_person', models.CharField(max_length=100, verbose_name='担当者名')),
                ('closing_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='締め日')),
                ('payment_due_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='支払期日')),
            ],
            options={
                'verbose_name': '会社情報',
                'verbose_name_plural': '会社情報',
            },
        ),
    ]
