# Generated by Django 5.1.5 on 2025-01-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bank_details',
            field=models.TextField(blank=True, null=True, verbose_name='銀行口座'),
        ),
    ]
