# Generated by Django 5.1.5 on 2025-01-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_bank_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seal',
            field=models.ImageField(blank=True, null=True, upload_to='seals/', verbose_name='会社印鑑'),
        ),
    ]
