# Generated by Django 5.1.5 on 2025-02-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_companyprofile_closing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(default='noreply@skm.sk-tokyo.net', max_length=254, verbose_name='送信元メールアドレス')),
            ],
            options={
                'verbose_name': 'メール設定',
                'verbose_name_plural': 'メール設定',
            },
        ),
    ]
