# Generated by Django 5.1.5 on 2025-02-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='sender_email',
            field=models.EmailField(default='info@sk-tokyo.net', max_length=254, verbose_name='送信元メールアドレス'),
        ),
    ]
