# Generated by Django 5.1.5 on 2025-02-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_emailsettings_sender_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
    ]
