# Generated by Django 5.1.5 on 2025-02-13 01:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='会社ロゴ'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='会社印鑑'),
        ),
    ]
