branch-defaults:
  main:
    environment: SKM-env
deploy:
  branch-defaults:
    main:
      environment: SKM-env
  environments:
  - SKM-env
global:
  application_name: SKM
  default_region: ap-northeast-1
  profile: null
