# Generated by Django 5.1.5 on 2025-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('stock_count', models.IntegerField(default=0, verbose_name='在庫数')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='商品コード')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images/', verbose_name='商品画像')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
