# Generated by Django 5.1.5 on 2025-01-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='カスタムフィールド'),
        ),
    ]
