# Generated by Django 5.1.5 on 2025-01-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='名前')),
                ('last_name', models.CharField(max_length=100, verbose_name='苗字')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='会社名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
            ],
        ),
    ]
