# Generated by Django 5.1.5 on 2025-01-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default='デフォルト会社名', max_length=255, verbose_name='会社名'),
        ),
    ]
