# Generated by Django 5.1.5 on 2025-02-13 00:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '顧客', 'verbose_name_plural': '顧客情報'},
        ),
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='会社ロゴ'),
        ),
    ]
