# Generated by Django 5.1.5 on 2025-02-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(choices=[('株式会社', '株式会社'), ('有限会社', '有限会社'), ('合同会社', '合同会社'), ('なし', 'なし')], default='なし', max_length=255, verbose_name='会社名'),
        ),
    ]
