# Generated by Django 5.1.5 on 2025-01-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docspdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='attention_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='宛先'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者名'),
        ),
    ]
