# Generated by Django 5.1.5 on 2025-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docspdf', '0002_quotation_attention_to_quotation_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='subtotal',
            field=models.PositiveIntegerField(verbose_name='小計'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='単価'),
        ),
    ]
