# Generated by Django 5.1.5 on 2025-01-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_company_name'),
        ('docspdf', '0003_alter_quotationitem_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者名')),
                ('attention_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='宛先')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='請求書番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='制作者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書一覧',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='品名')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_price', models.PositiveIntegerField(verbose_name='単価')),
                ('subtotal', models.PositiveIntegerField(verbose_name='小計')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='docspdf.invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '請求項目',
                'verbose_name_plural': '請求項目一覧',
            },
        ),
    ]
