# Generated by Django 5.1.5 on 2025-01-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docspdf', '0006_alter_quotationitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='project_name',
            field=models.CharField(default='未設定', max_length=200, verbose_name='案件名'),
        ),
    ]
