# Generated by Django 5.1.5 on 2025-02-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docspdf', '0008_invoice_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='納期'),
        ),
    ]
