# Generated by Django 5.1.5 on 2025-02-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_scheduled_at_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
    ]
