# Generated by Django 5.1.5 on 2025-01-21 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('clock_in', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
