name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # 本番環境用ブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          APPLICATION_NAME: "skw-django"  # AWS Elastic Beanstalk で設定したアプリケーション名
          ENVIRONMENT_NAME: "production-env"  # 本番環境
        run: |
          zip -r deploy.zip . -x "*.git*"
          aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket="elasticbeanstalk-ap-northeast-1-XXXXXXXXXX",S3Key="deploy.zip"
          aws elasticbeanstalk update-environment --application-name $APPLICATION_NAME --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
